spring:
    datasource:
        url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:postgres-db}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:clinix_datastore}
        username: ${SPRING_DATASOURCE_USERNAME:clinix_application}
        password: ${SPRING_DATASOURCE_PASSWORD:password}
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            idle-timeout: 300000
            max-lifetime: 1200000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: false
        defer-datasource-initialization: false

    sql:
        init:
            mode: never

    flyway:
        enabled: true
        clean-disabled: true
        baseline-version: 0
        locations: classpath:db/migration
        baseline-on-migrate: true

    docker:
        compose:
            enabled: false

springdoc:
    api-docs:
        enabled: false

management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics
    endpoint:
        health:
            show-details: when_authorized

clinix:
    security:
        jwt:
            secret: ${JWT_SECRET}
            expiration-ms: 1800000

logging:
    level:
        com.clinix: INFO
        org.springframework: ERROR
