server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:clinix_test_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false

  docker:
    compose:
      enabled: false

springdoc:
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health

clinix:
  security:
    jwt:
      secret: 7A25432A462D4A614E645267556B58703273357638792F423F4528482B4D6251
      expiration-ms: 3600000

logging:
  level:
    com.clinix: WARN
    org.springframework: WARN
